version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - GV_ZK_ARTIFACT_DIR=/data/zk
      - GV_CONSENT_LEDGER_DIR=/data/consent
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - pir1
      - pir2

  pir1:
    build:
      context: .
      dockerfile: Dockerfile.pir
    environment:
      - GV_PIR_FIXED_RESP_BYTES=65536
      - GV_PIR_JITTER_MS=8

  pir2:
    build:
      context: .
      dockerfile: Dockerfile.pir
    environment:
      - GV_PIR_FIXED_RESP_BYTES=65536
      - GV_PIR_JITTER_MS=8
