# .ruff.toml - Compatible with Ruff 0.4.x
[lint]
# Removed global ignores as per audit Task 3
# Previously had: extend-ignore = ["E501", "F401", "F541", "E722"]
# Now only keeping line length ignore
extend-ignore = ["E501"]

exclude = [
  "scripts/*",
  "tests/*",
]

[lint.per-file-ignores]
"tools/*.py" = ["ALL"]        # silence helper scripts
"examples/*.py" = ["E402"]    # allow imports after setup/config in examples
