[output]
max-violations = 200

# .ruff.toml - Compatible with Ruff 0.4.x
[lint]
extend-ignore = ["E501"]

exclude = [
  "scripts/*",
  "tests/*",
]

[lint.per-file-ignores]
"tools/*.py" = ["ALL"]        # silence helper scripts
