version: "3.8"
services:
  api:
    extends:
      service: api
      file: docker-compose.yml
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: gv_prometheus
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss:10.4.5
    container_name: gv_grafana
    ports:
      - "3000:3000"
    volumes:
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning:ro
