version: "3.8"
services:
  api:
    build:
      context: .
    image: genomevault/api:local
    container_name: genomevault_api
    ports:
      - "8000:8000"
    environment:
      - UVICORN_WORKERS=2
    command: ["uvicorn", "genomevault.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
