#!/bin/bash
# GitHub Push Commands for GenomeVault

echo "📦 GenomeVault - GitHub Push Commands"
echo "===================================="
echo ""
echo "1️⃣  First, initialize git repository (if not already done):"
echo "   git init"
echo ""
echo "2️⃣  Add all files to staging:"
echo "   git add ."
echo ""
echo "3️⃣  Create your initial commit:"
echo "   git commit -m \"Initial commit: GenomeVault 3.0 - Privacy-preserving genomics platform\""
echo ""
echo "4️⃣  Create a new repository on GitHub:"
echo "   - Go to https://github.com/new"
echo "   - Name it: genomevault"
echo "   - Choose Private or Public"
echo "   - DON'T initialize with README (you already have one)"
echo ""
echo "5️⃣  Link your local repo to GitHub (replace YOUR_USERNAME):"
echo "   git remote add origin https://github.com/YOUR_USERNAME/genomevault.git"
echo ""
echo "6️⃣  Push to GitHub:"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "📝 Complete command sequence:"
echo "----------------------------"
echo ""
echo "git init"
echo "git add ."
echo "git commit -m \"Initial commit: GenomeVault 3.0 - Privacy-preserving genomics platform\""
echo "git remote add origin https://github.com/YOUR_USERNAME/genomevault.git"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "🔐 If you're using SSH instead of HTTPS:"
echo "   git remote add origin git@github.com:YOUR_USERNAME/genomevault.git"
echo ""
echo "✅ After pushing, consider:"
echo "   - Adding a description to your GitHub repo"
echo "   - Setting topics: genomics, privacy, zero-knowledge-proofs, blockchain"
echo "   - Enabling Issues and Discussions"
echo "   - Setting up branch protection rules"
