[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
    | __pycache__
    | \.pytest_cache
    | build
    | dist
    | \.venv
    | \.env
    | genomevault\.egg-info
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
skip = ["__pycache__", ".git", ".pytest_cache", "build", "dist", "genomevault.egg-info"]

[tool.pylint.messages_control]
disable = [
    "C0103",  # Invalid name
    "C0114",  # Missing module docstring
    "C0115",  # Missing class docstring
    "C0116",  # Missing function docstring
    "R0903",  # Too few public methods
    "R0913",  # Too many arguments
    "W0613",  # Unused argument
    "R0801",  # Similar lines in files (we'll handle with TailChasingFixer)
]

[tool.pylint.format]
max-line-length = 88
