[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[project]
name = "genomevault"
version = "0.1.0"
description = "GenomeVault — privacy-preserving genomic compute (ZK/PIR/HDC)"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{ name = "Rohan Vinaik" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Typing :: Typed",
]
dependencies = []

[project.optional-dependencies]
dev = ["ruff", "mypy", "pytest", "pytest-cov", "pyupgrade", "radon"]

[tool.hatch.build.targets.wheel]
packages = ["genomevault"]

[project.scripts]
genomevault = "genomevault.cli:main"
gv = "genomevault.cli:main"
