line-length = 100
target-version = "py311"

[lint]
# Start with a more lenient configuration
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
]
ignore = [
    "E203",  # whitespace before ':'
    "E266",  # too many leading '#' for block comment
    "E501",  # line too long (handled by formatter)
    "F401",  # imported but unused (temporarily)
    "F841",  # local variable assigned but never used (temporarily)
]

[format]
quote-style = "preserve"

# Note: After initial cleanup, gradually enable more rules:
# "B",    # flake8-bugbear
# "UP",   # pyupgrade  
# "RUF",  # Ruff-specific rules
