"""Core constants for GenomeVault."""

# Hypervector constants
HYPERVECTOR_DIMENSIONS = 10000
DEFAULT_SPARSITY = 0.1

# Security constants
DEFAULT_SECURITY_LEVEL = 128
MAX_VARIANTS = 1000
VERIFICATION_TIME_MAX = 30.0

# ZK Proof constants
DEFAULT_CIRCUIT_SIZE = 1024
MAX_PROOF_SIZE = 1024 * 1024  # 1MB

# Node types and weights
NODE_CLASS_WEIGHT = {"VALIDATOR": 3, "COMPUTE": 2, "STORAGE": 1, "CLIENT": 0}
