---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genomevault-api
  labels:
    app: genomevault-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: genomevault-api
  template:
    metadata:
      labels:
        app: genomevault-api
    spec:
      containers:
        - name: api
          image: genomevault/api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
