---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genomevault-monitoring
  namespace: genomevault
  labels:
    app: genomevault
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genomevault
      component: monitoring
  template:
    metadata:
      labels:
        app: genomevault
        component: monitoring
    spec:
      serviceAccountName: genomevault-monitoring

      containers:
      - name: prometheus
        image: prom/prometheus:v2.40.0
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
        - '--web.enable-lifecycle'

        ports:
        - name: http
          containerPort: 9090
          protocol: TCP

        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /prometheus

      - name: grafana
        image: grafana/grafana:9.3.0

        ports:
        - name: http
          containerPort: 3000
          protocol: TCP

        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: genomevault-monitoring-secrets
              key: grafana-admin-password

        volumeMounts:
        - name: grafana-config
          mountPath: /etc/grafana
        - name: grafana-data
          mountPath: /var/lib/grafana

      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data
      - name: grafana-config
        configMap:
          name: grafana-config
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
