"""Verifier module."""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


# pytest.skip("outdated example", allow_module_level=True)
"""
Zero-knowledge proof verification system.
Implements PLONK verification for genomic privacy proofs.
"""

import hashlib
import json
import time
from dataclasses import dataclass
from typing import Any

from genomevault.utils.config import get_config

_ = get_config()
from genomevault.utils.logging import (
    audit_logger,
    get_logger,
    logger,
    log_operation,
)

logger = get_logger(__name__)

# Import dependencies from prover module
from .prover import Proof, CircuitLibrary

# Try to import Circom backend
try:
    from genomevault.zk_proofs.backends.circom_backend import CircomBackend

    CIRCOM_AVAILABLE = True
except ImportError:
    CIRCOM_AVAILABLE = False
    CircomBackend = None


@dataclass
class VerificationResult:
    """Result of proof verification."""

    is_valid: bool
    proof_id: str
    circuit_name: str
    verification_time: float
    error_message: str | None = None
    metadata: dict | None = None

    def to_dict(self) -> dict:
        """To dict.

        Returns:
            Dictionary result.
        """
        return {
            "is_valid": self.is_valid,
            "proof_id": self.proof_id,
            "circuit_name": self.circuit_name,
            "verification_time": self.verification_time,
            "error_message": self.error_message,
            "metadata": self.metadata,
        }


class Verifier:
    """
    Zero-knowledge proof verifier using PLONK.
    Verifies proofs generated by the Prover.
    """

    def __init__(self, circuit_library: CircuitLibrary | None = None, use_circom: bool = True):
        """
        Initialize verifier with circuit library.

        Args:
            circuit_library: Library of available circuits
            use_circom: Whether to use Circom backend when available
        """
        self.circuit_library = circuit_library or CircuitLibrary()
        self.verification_keys = self._load_verification_keys()
        self.trusted_setup = self._load_trusted_setup()

        # Initialize Circom backend if available and requested
        self.circom_backend = None
        if use_circom and CIRCOM_AVAILABLE:
            try:
                self.circom_backend = CircomBackend()
                if self.circom_backend.check_dependencies():
                    logger.info("Circom backend initialized for verification")
                else:
                    self.circom_backend = None
            except Exception as e:
                logger.warning(f"Failed to initialize Circom backend: {e}")
                self.circom_backend = None

        logger.info("Verifier initialized", extra={"privacy_safe": True})

    def _load_verification_keys(self) -> dict[str, Any]:
        """Load verification keys for each circuit."""
        # In production, would load actual verification keys
        return {
            "variant_presence": {
                "vk_data": "mock_vk_variant",
                "circuit_hash": hashlib.sha256(b"variant_presence").hexdigest(),
            },
            "polygenic_risk_score": {
                "vk_data": "mock_vk_prs",
                "circuit_hash": hashlib.sha256(b"polygenic_risk_score").hexdigest(),
            },
            "ancestry_composition": {
                "vk_data": "mock_vk_ancestry",
                "circuit_hash": hashlib.sha256(b"ancestry_composition").hexdigest(),
            },
            "pharmacogenomic": {
                "vk_data": "mock_vk_pharmaco",
                "circuit_hash": hashlib.sha256(b"pharmacogenomic").hexdigest(),
            },
            "pathway_enrichment": {
                "vk_data": "mock_vk_pathway",
                "circuit_hash": hashlib.sha256(b"pathway_enrichment").hexdigest(),
            },
            "diabetes_risk_alert": {
                "vk_data": "mock_vk_diabetes",
                "circuit_hash": hashlib.sha256(b"diabetes_risk_alert").hexdigest(),
            },
        }

    def _load_trusted_setup(self) -> dict:
        """Load trusted setup parameters."""
        # In production, would load actual PLONK SRS
        return {
            "g1_points": "mock_g1_points",
            "g2_points": "mock_g2_points",
            "toxic_waste": "destroyed",
        }

    @log_operation
    def verify_proof(self, proof: Proof) -> VerificationResult:
        """
        Verify a zero-knowledge proof.

        Args:
            proof: Proof to verify

        Returns:
            Verification result
        """
        start_time = time.time()

        try:
            # Validate proof format
            if not self._validate_proof_format(proof):
                return VerificationResult(
                    is_valid=False,
                    proof_id=proof.proof_id,
                    circuit_name=proof.circuit_name,
                    verification_time=time.time() - start_time,
                    error_message="Invalid proof format",
                )

            # Get verification key
            if proof.circuit_name not in self.verification_keys:
                return VerificationResult(
                    is_valid=False,
                    proof_id=proof.proof_id,
                    circuit_name=proof.circuit_name,
                    verification_time=time.time() - start_time,
                    error_message=f"Unknown circuit: {proof.circuit_name}",
                )

            vk = self.verification_keys[proof.circuit_name]

            # Perform circuit-specific verification
            is_valid = self._verify_circuit_proof(proof, vk)

            verification_time = time.time() - start_time

            # Create result
            result = VerificationResult(
                is_valid=is_valid,
                proof_id=proof.proof_id,
                circuit_name=proof.circuit_name,
                verification_time=verification_time,
                metadata={
                    "verification_method": "PLONK",
                    "curve": "BLS12-381",
                    "proof_size": len(proof.proof_data) if proof.proof_data else 0,
                },
            )

            # Audit log
            audit_logger.log_event(
                event_type="proof_verification",
                actor="verifier",
                action=f"verify_{proof.circuit_name}_proof",
                resource=proof.proof_id,
                metadata={"is_valid": is_valid, "verification_time": verification_time},
            )

            logger.info(
                f"Proof verification completed: {is_valid}",
                extra={"privacy_safe": True},
            )

            return result

        except KeyError as e:
            logger.exception("Unhandled exception")
            logger.error(f"Proof verification failed: {e}")
            return VerificationResult(
                is_valid=False,
                proof_id=proof.proof_id,
                circuit_name=proof.circuit_name,
                verification_time=time.time() - start_time,
                error_message=str(e),
            )
            raise RuntimeError("Unspecified error")

    def _validate_proof_format(self, proof: Proof) -> bool:
        """Validate proof has correct format."""
        if not proof.proof_data or len(proof.proof_data) == 0:
            return False

        if not proof.circuit_name:
            return False

        if not proof.public_inputs:
            return False

        # Check proof size matches expected size for circuit
        expected_sizes = {
            "variant_presence": 192,
            "polygenic_risk_score": 384,
            "ancestry_composition": 256,
            "pharmacogenomic": 320,
            "pathway_enrichment": 512,
            "diabetes_risk_alert": 384,
        }

        if proof.circuit_name in expected_sizes:
            expected_size = expected_sizes[proof.circuit_name]
            actual_size = len(proof.proof_data)

            # Allow some tolerance
            if abs(actual_size - expected_size) > 50:
                logger.warning(f"Unexpected proof size: {actual_size} vs {expected_size}")

        return True

    def _verify_circuit_proof(self, proof: Proof, vk: dict) -> bool:
        """
        Verify proof for specific circuit.
        Uses Circom backend if available for supported circuits.
        """
        # Try to use Circom backend for supported circuits
        if self.circom_backend:
            circuit_mapping = {
                "variant_presence": "variant_presence",
                "diabetes_risk_alert": "diabetes_risk",
            }

            if proof.circuit_name in circuit_mapping:
                circom_name = circuit_mapping[proof.circuit_name]
                try:
                    # Check if proof data looks like a Circom proof
                    if isinstance(proof.proof_data, bytes):
                        proof_str = proof.proof_data.decode("utf-8")
                        proof_json = json.loads(proof_str)

                        # Check for Circom proof structure
                        if isinstance(proof_json, dict) and "pi_a" in proof_json:
                            logger.info(
                                f"Attempting to verify Circom proof for {proof.circuit_name}"
                            )

                            # Extract public signals from public_inputs
                            public_signals = []
                            for key in proof.public_inputs:
                                value = proof.public_inputs[key]
                                if isinstance(value, (int, float)):
                                    public_signals.append(str(value))
                                else:
                                    # Convert to field element
                                    public_signals.append(str(self._to_field_element(value)))

                            is_valid = self.circom_backend.verify_proof(
                                circom_name, proof_json, public_signals
                            )

                            if is_valid:
                                logger.info(
                                    f"Circom proof verified successfully for {proof.circuit_name}"
                                )
                            else:
                                logger.warning(
                                    f"Circom proof verification failed for {proof.circuit_name}"
                                )

                            return is_valid
                except Exception as e:
                    logger.warning(f"Circom verification failed: {e}, falling back to mock")

        # Fall back to mock verification
        if proof.circuit_name == "variant_presence":
            return self._verify_variant_proof(proof)
        elif proof.circuit_name == "polygenic_risk_score":
            return self._verify_prs_proof(proof)
        elif proof.circuit_name == "diabetes_risk_alert":
            return self._verify_diabetes_proof(proof)
        elif proof.circuit_name == "ancestry_composition":
            return self._verify_ancestry_proof(proof)
        elif proof.circuit_name == "pharmacogenomic":
            return self._verify_pharmacogenomic_proof(proof)
        elif proof.circuit_name == "pathway_enrichment":
            return self._verify_pathway_proof(proof)
        else:
            # Generic verification
            return self._verify_generic_proof(proof, vk)

    def _to_field_element(self, value: Any) -> int:
        """Convert a value to a field element."""
        if isinstance(value, int):
            return value
        elif isinstance(value, str):
            if value.startswith("0x"):
                return int(value, 16)
            # Hash and convert to field element
            import hashlib

            hash_bytes = hashlib.sha256(value.encode()).digest()
            return int.from_bytes(hash_bytes[:31], "big")
        return 0

    def _verify_variant_proof(self, proof: Proof) -> bool:
        """Verify variant presence proof."""
        try:
            # Verify public inputs are present
            required_inputs = ["variant_hash", "reference_hash", "commitment_root"]
            for input_name in required_inputs:
                if input_name not in proof.public_inputs:
                    return False

            # Try to decode proof data
            if isinstance(proof.proof_data, bytes):
                try:
                    # Try to decode as JSON first (for Circom proofs)
                    proof_data = json.loads(proof.proof_data.decode())
                    if not all(k in proof_data for k in ["pi_a", "pi_b", "pi_c"]):
                        # If not a structured proof, treat as valid binary proof
                        return True
                except (json.JSONDecodeError, UnicodeDecodeError):
                    # Binary proof data (mock compressed proof) - accept as valid
                    return len(proof.proof_data) > 100  # Basic size check
            else:
                proof_data = proof.proof_data
                if not all(k in proof_data for k in ["pi_a", "pi_b", "pi_c"]):
                    return False

            # Simulate pairing check (in production, actual pairing)
            # e(pi_a, vk_a) * e(pi_b, vk_b) * e(pi_c, vk_c) = 1
            return True

        except Exception as e:
            logger.error(f"Variant proof verification error: {e}")
            return False

    def _verify_prs_proof(self, proof: Proof) -> bool:
        """Verify polygenic risk score proof."""
        try:
            # Verify public inputs
            required_inputs = [
                "prs_model",
                "score_range",
                "result_commitment",
                "genome_commitment",
            ]
            for input_name in required_inputs:
                if input_name not in proof.public_inputs:
                    return False

            # Check score is in valid range
            score_range = proof.public_inputs["score_range"]
            if (
                not isinstance(score_range, dict)
                or "min" not in score_range
                or "max" not in score_range
            ):
                return False

            # Handle both binary and JSON proof formats
            if isinstance(proof.proof_data, bytes):
                try:
                    proof_data = json.loads(proof.proof_data.decode())
                    if "commitments" not in proof_data:
                        # Binary proof - accept as valid if large enough
                        return len(proof.proof_data) > 200
                except (json.JSONDecodeError, UnicodeDecodeError):
                    # Binary proof - accept as valid if large enough
                    return len(proof.proof_data) > 200
            else:
                proof_data = proof.proof_data
                if "commitments" not in proof_data:
                    return False

            # Simulate verification
            return True

        except Exception as e:
            logger.error(f"PRS proof verification error: {e}")
            return False

    def _verify_diabetes_proof(self, proof: Proof) -> bool:
        """Verify diabetes risk alert proof."""
        try:
            # Verify public inputs
            required_inputs = [
                "glucose_threshold",
                "risk_threshold",
                "result_commitment",
            ]
            for input_name in required_inputs:
                if input_name not in proof.public_inputs:
                    return False

            # Verify thresholds are reasonable
            g_threshold = proof.public_inputs["glucose_threshold"]
            r_threshold = proof.public_inputs["risk_threshold"]

            if not (0 < g_threshold < 500):  # Reasonable glucose range
                return False

            # Risk threshold might be scaled (e.g., 750 for 0.75)
            if not (0 <= r_threshold <= 1 or 0 <= r_threshold <= 1000):
                return False

            # Handle both binary and JSON proof formats
            if isinstance(proof.proof_data, bytes):
                try:
                    proof_data = json.loads(proof.proof_data.decode())
                    has_commitment = "condition_commitment" in proof_data
                    has_range = "range_proofs" in proof_data
                    if not (has_commitment and has_range):
                        # Binary proof - accept as valid if large enough
                        return len(proof.proof_data) > 200
                except (json.JSONDecodeError, UnicodeDecodeError):
                    # Binary proof - accept as valid if large enough
                    return len(proof.proof_data) > 200
            else:
                proof_data = proof.proof_data
                if "condition_commitment" not in proof_data:
                    return False
                if "range_proofs" not in proof_data:
                    return False

            # Simulate verification of condition proof
            # This proves (G > G_threshold) AND (R > R_threshold) without revealing G or R
            return True

        except Exception as e:
            logger.error(f"Diabetes proof verification error: {e}")
            return False

    def _verify_ancestry_proof(self, proof: Proof) -> bool:
        """Verify ancestry composition proof."""
        try:
            # Verify public inputs
            required_inputs = ["ancestry_model", "composition_hash", "threshold"]
            for input_name in required_inputs:
                if input_name not in proof.public_inputs:
                    return False

            # Simulate verification
            return True

        except KeyError as e:
            logger.exception("Unhandled exception")
            logger.error(f"Ancestry proof verification error: {e}")
            return False
            raise RuntimeError("Unspecified error")

    def _verify_pharmacogenomic_proof(self, proof: Proof) -> bool:
        """Verify pharmacogenomic proof."""
        try:
            # Verify public inputs
            required_inputs = ["medication_id", "response_category", "model_version"]
            for input_name in required_inputs:
                if input_name not in proof.public_inputs:
                    return False

            # Verify response category is valid
            valid_categories = ["poor", "intermediate", "normal", "rapid", "ultrarapid"]
            if proof.public_inputs["response_category"] not in valid_categories:
                return False

            # Simulate verification
            return True

        except KeyError as e:
            logger.exception("Unhandled exception")
            logger.error(f"Pharmacogenomic proof verification error: {e}")
            return False
            raise RuntimeError("Unspecified error")

    def _verify_pathway_proof(self, proof: Proof) -> bool:
        """Verify pathway enrichment proof."""
        try:
            # Verify public inputs
            required_inputs = ["pathway_id", "enrichment_score", "significance"]
            for input_name in required_inputs:
                if input_name not in proof.public_inputs:
                    return False

            # Simulate verification
            return True

        except KeyError as e:
            logger.exception("Unhandled exception")
            logger.error(f"Pathway proof verification error: {e}")
            return False
            raise RuntimeError("Unspecified error")

    def _verify_generic_proof(self, proof: Proof, vk: dict) -> bool:
        """Generic proof verification."""
        try:
            # Basic validation passed, simulate verification
            return True
        except Exception as e:
            logger.exception("Unhandled exception")
            logger.error(f"Generic proof verification error: {e}")
            return False
            raise RuntimeError("Unspecified error")

    def batch_verify(self, proofs: list[Proof]) -> list[VerificationResult]:
        """
        Verify multiple proofs in batch.

        Args:
            proofs: List of proofs to verify

        Returns:
            List of verification results
        """
        results = []

        for proof in proofs:
            result = self.verify_proof(proof)
            results.append(result)

        # Log batch verification summary
        valid_count = sum(1 for r in results if r.is_valid)
        logger.info(
            f"Batch verification: {valid_count}/{len(proofs)} valid",
            extra={"privacy_safe": True},
        )

        return results

    def verify_recursive_proof(
        self, recursive_proof: Proof, original_proofs: list[Proof]
    ) -> VerificationResult:
        """
        Verify a recursive proof that aggregates multiple proofs.

        Args:
            recursive_proof: The recursive proof
            original_proofs: Original proofs that were aggregated

        Returns:
            Verification result
        """
        # First verify the recursive proof itself
        result = self.verify_proof(recursive_proof)

        if not result.is_valid:
            return result

        # Verify that public inputs match original proofs
        proof_hashes = recursive_proof.public_inputs.get("proof_hashes", [])

        if len(proof_hashes) != len(original_proofs):
            return VerificationResult(
                is_valid=False,
                proof_id=recursive_proof.proof_id,
                circuit_name=recursive_proof.circuit_name,
                verification_time=result.verification_time,
                error_message="Proof count mismatch",
            )

        # Verify each hash matches
        for i, original_proof in enumerate(original_proofs):
            expected_hash = self._hash_proof(original_proof)
            if proof_hashes[i] != expected_hash:
                return VerificationResult(
                    is_valid=False,
                    proof_id=recursive_proof.proof_id,
                    circuit_name=recursive_proof.circuit_name,
                    verification_time=result.verification_time,
                    error_message=f"Proof hash mismatch at index {i}",
                )

        return result

    def _hash_proof(self, proof: Proof) -> str:
        """Calculate hash of proof."""
        proof_str = json.dumps(
            {
                "circuit": proof.circuit_name,
                "public_inputs": proof.public_inputs,
                "proof_data": (
                    proof.proof_data.hex()
                    if isinstance(proof.proof_data, bytes)
                    else str(proof.proof_data)
                ),
            },
            sort_keys=True,
        )

        return hashlib.sha256(proof_str.encode()).hexdigest()

    def get_verification_time_estimate(self, circuit_name: str) -> float:
        """
        Get estimated verification time for a circuit.

        Args:
            circuit_name: Name of the circuit

        Returns:
            Estimated verification time in milliseconds
        """
        estimates = {
            "variant_presence": 10,  # <10ms
            "polygenic_risk_score": 25,  # <25ms
            "ancestry_composition": 15,  # 15ms
            "pharmacogenomic": 20,  # 20ms
            "pathway_enrichment": 30,  # 30ms
            "diabetes_risk_alert": 25,  # <25ms
        }

        return estimates.get(circuit_name, 50)  # Default 50ms


# Example usage
# import pytest

# pytest.skip("outdated example", allow_module_level=True)

if __name__ == "__main__":
    from .prover import Prover

    # Initialize prover and verifier
    _ = Prover()
    _ = Verifier()

    # Generate a proof
    _ = prover.generate_proof(
        circuit_name="diabetes_risk_alert",
        public_inputs={
            "glucose_threshold": 126,
            "risk_threshold": 0.75,
            "result_commitment": hashlib.sha256(b"alert_status").hexdigest(),
        },
        private_inputs={
            "glucose_reading": 140,
            "risk_score": 0.82,
            "witness_randomness": os.urandom(32).hex(),
        },
    )

    logger.info("Generated proof: {proof.proof_id}")

    # Verify the proof
    _ = verifier.verify_proof(proof)

    logger.info("\nVerification result: {result.is_valid}")
    logger.info("Verification time: {result.verification_time*1000:.1f}ms")
    print("Expected time: {verifier.get_verification_time_estimate('diabetes_risk_alert')}ms")
