apiVersion: v1
kind: Service
metadata:
  name: genomevault-monitoring
  namespace: genomevault
  labels:
    app: genomevault
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: genomevault
    component: monitoring
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
