---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-api
  namespace: genomevault
  labels:
    app: genomevault
    component: api
spec:
  type: LoadBalancer
  selector:
    app: genomevault
    component: api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-blockchain
  namespace: genomevault
  labels:
    app: genomevault
    component: blockchain
spec:
  type: ClusterIP
  selector:
    app: genomevault
    component: blockchain
  ports:
  - port: 26656
    targetPort: 26656
    protocol: TCP
    name: p2p
  - port: 26657
    targetPort: 26657
    protocol: TCP
    name: rpc
  - port: 26660
    targetPort: 26660
    protocol: TCP
    name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-blockchain-public
  namespace: genomevault
  labels:
    app: genomevault
    component: blockchain-public
spec:
  type: LoadBalancer
  selector:
    app: genomevault
    component: blockchain
  ports:
  - port: 26657
    targetPort: 26657
    protocol: TCP
    name: rpc
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-pir-server
  namespace: genomevault
  labels:
    app: genomevault
    component: pir-server
spec:
  type: ClusterIP
  selector:
    app: genomevault
    component: pir-server
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-pir-lb
  namespace: genomevault
  labels:
    app: genomevault
    component: pir-lb
spec:
  type: LoadBalancer
  selector:
    app: genomevault
    component: pir-server
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-monitoring
  namespace: genomevault
  labels:
    app: genomevault
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: prometheus
