---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-api
  namespace: genomevault
  labels:
    app: genomevault
    component: api
spec:
  type: LoadBalancer
  selector:
    app: genomevault
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
