apiVersion: v1
kind: Service
metadata:
  name: genomevault-blockchain-public
  namespace: genomevault
  labels:
    app: genomevault
    component: blockchain
spec:
  type: LoadBalancer
  selector:
    app: genomevault
    component: blockchain
  ports:
  - name: rpc
    port: 26657
    targetPort: 26657
    protocol: TCP
