apiVersion: v1
kind: Service
metadata:
  name: genomevault-api
  namespace: genomevault
  labels:
    app: genomevault
    component: api
spec:
  type: LoadBalancer
  selector:
    app: genomevault
    component: api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
    
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-blockchain
  namespace: genomevault
  labels:
    app: genomevault
    component: blockchain
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: genomevault
    component: blockchain
  ports:
  - name: p2p
    port: 26656
    targetPort: 26656
    protocol: TCP
  - name: rpc
    port: 26657
    targetPort: 26657
    protocol: TCP
  - name: prometheus
    port: 26660
    targetPort: 26660
    protocol: TCP
    
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-blockchain-public
  namespace: genomevault
  labels:
    app: genomevault
    component: blockchain
spec:
  type: LoadBalancer
  selector:
    app: genomevault
    component: blockchain
  ports:
  - name: rpc
    port: 26657
    targetPort: 26657
    protocol: TCP
    
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-pir-server
  namespace: genomevault
  labels:
    app: genomevault
    component: pir-server
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: genomevault
    component: pir-server
  ports:
  - name: pir
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
    
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-pir-lb
  namespace: genomevault
  labels:
    app: genomevault
    component: pir-server
spec:
  type: LoadBalancer
  selector:
    app: genomevault
    component: pir-server
  ports:
  - name: pir
    port: 8080
    targetPort: 8080
    protocol: TCP
    
---
apiVersion: v1
kind: Service
metadata:
  name: genomevault-monitoring
  namespace: genomevault
  labels:
    app: genomevault
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: genomevault
    component: monitoring
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    protocol: TCP
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
