apiVersion: v1
kind: ConfigMap
metadata:
  name: genomevault-config
  namespace: genomevault
data:
  # Core configuration
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  API_PORT: "8000"

  # Hypervector configuration
  HYPERVECTOR_DIMENSIONS: "10000"
  COMPRESSION_TIERS: "mini,clinical,full"

  # PIR configuration
  PIR_SERVER_COUNT: "5"
  PIR_SHARD_COUNT: "3"
  PIR_CACHE_SIZE: "1GB"

  # Blockchain configuration
  BLOCKCHAIN_NETWORK: "mainnet"
  BLOCK_TIME_SECONDS: "5"
  CONSENSUS_ALGORITHM: "tendermint"

  # Privacy configuration
  DIFFERENTIAL_PRIVACY_EPSILON: "1.0"
  DIFFERENTIAL_PRIVACY_DELTA: "1e-6"

  # Storage configuration
  STORAGE_BACKEND: "s3"
  BACKUP_RETENTION_DAYS: "30"

  # Monitoring configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
