"""
Alembic environment configuration for GenomeVault database migrations.

This module configures the Alembic migration environment with support for:
- Async database operations
- Automatic schema detection
- Partitioned tables for time-series data
- HIPAA-compliant audit logging
"""

import os
import sys
import logging
from logging.config import fileConfig
from pathlib import Path

from sqlalchemy import engine_from_config, pool, text
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine
from alembic import context

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

# Import GenomeVault models
from genomevault.models import Base
from genomevault.models.user import User, Role, Permission
from genomevault.models.audit import AuditLog, PHIAccessLog
from genomevault.models.genomic import GenomicDataMetadata, HypervectorStorage
from genomevault.models.query import QueryHistory, DifferentialPrivacyLog

# This is the Alembic Config object
config = context.config

# Interpret the config file for Python logging
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Add your model's MetaData object here for 'autogenerate' support
target_metadata = Base.metadata

# Get database URL from environment variable
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://genomevault:genomevault@localhost/genomevault"
)

# Convert to async URL if needed
if DATABASE_URL.startswith("postgresql://"):
    ASYNC_DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+asyncpg://")
else:
    ASYNC_DATABASE_URL = DATABASE_URL

# Override the sqlalchemy.url in the alembic config
config.set_main_option("sqlalchemy.url", DATABASE_URL)

# Custom configuration for GenomeVault
GENOMEVAULT_CONFIG = {
    "use_partitioning": os.getenv("USE_PARTITIONING", "true").lower() == "true",
    "partition_interval": os.getenv("PARTITION_INTERVAL", "monthly"),  # daily, weekly, monthly, yearly
    "retention_days": {
        "audit_logs": int(os.getenv("AUDIT_RETENTION_DAYS", "2555")),  # 7 years for HIPAA
        "query_history": int(os.getenv("QUERY_RETENTION_DAYS", "365")),
        "genomic_metadata": int(os.getenv("GENOMIC_RETENTION_DAYS", "3650")),  # 10 years
    },
    "enable_encryption": os.getenv("ENABLE_DB_ENCRYPTION", "true").lower() == "true",
}


def include_object(object, name, type_, reflected, compare_to):
    """
    Filter objects for Alembic autogenerate.
    
    This function determines which database objects should be included
    in autogenerated migrations.
    """
    # Skip PostgreSQL internal schemas
    if type_ == "schema":
        return name not in ["pg_catalog", "information_schema", "pg_toast"]
    
    # Skip temporary tables
    if type_ == "table" and name.startswith("tmp_"):
        return False
    
    # Include everything else
    return True


def process_revision_directives(context, revision, directives):
    """
    Process revision directives for custom migration logic.
    
    This function can modify the generated migration scripts to add
    custom logic like partition creation or index optimization.
    """
    if config.cmd_opts and hasattr(config.cmd_opts, 'autogenerate'):
        script = directives[0]
        
        # Add custom imports if needed
        if GENOMEVAULT_CONFIG["use_partitioning"]:
            script.imports.add("from sqlalchemy import text")
            script.imports.add("from datetime import datetime, timedelta")
        
        # Log the migration
        logging.info(f"Generating migration: {revision}")


def create_partitions(connection, table_name, partition_type="range", interval="monthly"):
    """
    Create partitioned tables for time-series data.
    
    This is used for audit logs and query history to improve performance
    and enable efficient data retention policies.
    """
    if partition_type == "range" and interval == "monthly":
        # Create partitions for the next 12 months
        for i in range(12):
            partition_date = f"DATE '2025-{i+1:02d}-01'"
            next_date = f"DATE '2025-{i+2:02d}-01'" if i < 11 else f"DATE '2026-01-01'"
            partition_name = f"{table_name}_2025_{i+1:02d}"
            
            sql = text(f"""
                CREATE TABLE IF NOT EXISTS {partition_name}
                PARTITION OF {table_name}
                FOR VALUES FROM ({partition_date}) TO ({next_date});
            """)
            connection.execute(sql)
            
            # Create indexes on partition
            connection.execute(text(f"""
                CREATE INDEX IF NOT EXISTS idx_{partition_name}_created_at
                ON {partition_name} (created_at);
            """))


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode.
    
    This configures the context with just a URL and not an Engine,
    though an Engine is acceptable here as well. By skipping the Engine
    creation we don't even need a DBAPI to be available.
    
    Calls to context.execute() here emit the given string to the
    script output.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        process_revision_directives=process_revision_directives,
        compare_type=True,
        compare_server_default=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode.
    
    In this scenario we need to create an Engine and associate a
    connection with the context.
    """
    # Create connection pool configuration
    poolclass = pool.NullPool if os.getenv("DB_POOL_DISABLED") else None
    
    configuration = config.get_section(config.config_ini_section)
    configuration['sqlalchemy.url'] = DATABASE_URL
    
    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=poolclass,
    )

    with connectable.connect() as connection:
        # Enable necessary PostgreSQL extensions
        connection.execute(text("CREATE EXTENSION IF NOT EXISTS pg_trgm;"))  # For text search
        connection.execute(text("CREATE EXTENSION IF NOT EXISTS pgcrypto;"))  # For encryption
        connection.execute(text("CREATE EXTENSION IF NOT EXISTS btree_gin;"))  # For composite indexes
        connection.execute(text("CREATE EXTENSION IF NOT EXISTS btree_gist;"))  # For exclusion constraints
        
        # Set up row-level security if enabled
        if GENOMEVAULT_CONFIG["enable_encryption"]:
            connection.execute(text("""
                -- Enable row-level security on sensitive tables
                ALTER TABLE users ENABLE ROW LEVEL SECURITY;
                ALTER TABLE phi_access_logs ENABLE ROW LEVEL SECURITY;
                ALTER TABLE genomic_data_metadata ENABLE ROW LEVEL SECURITY;
            """))
        
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            process_revision_directives=process_revision_directives,
            compare_type=True,
            compare_server_default=True,
            # Custom render functions for PostgreSQL-specific types
            render_item=render_item,
        )

        with context.begin_transaction():
            context.run_migrations()
            
            # Create partitions after migrations
            if GENOMEVAULT_CONFIG["use_partitioning"]:
                create_partitions(connection, "audit_logs", "range", "monthly")
                create_partitions(connection, "phi_access_logs", "range", "monthly")
                create_partitions(connection, "query_history", "range", "daily")


def render_item(type_, obj, autogen_context):
    """
    Custom rendering for PostgreSQL-specific types.
    
    This function handles rendering of custom types like JSONB, arrays,
    and other PostgreSQL-specific features.
    """
    if type_ == "type" and isinstance(obj, str):
        # Handle PostgreSQL array types
        if obj.endswith("[]"):
            return f"postgresql.ARRAY({obj[:-2]})"
        # Handle JSONB
        if obj == "jsonb":
            return "postgresql.JSONB"
    
    # Default rendering
    return False


async def run_async_migrations():
    """
    Run migrations using async engine (for async SQLAlchemy).
    
    This is useful when the application uses async database operations.
    """
    engine = create_async_engine(ASYNC_DATABASE_URL, echo=True)
    
    async with engine.begin() as conn:
        await conn.run_sync(do_run_migrations)
    
    await engine.dispose()


def do_run_migrations(connection):
    """
    Execute migrations with the given connection.
    
    This is used by the async migration runner.
    """
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        process_revision_directives=process_revision_directives,
    )
    
    with context.begin_transaction():
        context.run_migrations()


# Determine which mode to run migrations in
if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()