name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff mypy
      - name: Fail if any file is stubbed
        run: |
          python scripts/check_no_stubs.py
      - name: Lint
        run: ruff check .
      - name: Typecheck
        run: mypy --ignore-missing-imports . || true
      - name: Tests
        run: pytest -q
