name: CI

on:
  push:
    branches: [ main, clean-slate, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt
        pip install ruff pytest pytest-cov

    - name: Lint with ruff
      run: |
        ruff check genomevault
      continue-on-error: true

    - name: Test with pytest
      run: |
        pytest tests/ -v --cov=genomevault --cov-report=xml
      continue-on-error: true

    - name: Check API startup
      run: |
        python -m genomevault.api.main &
        sleep 5
        curl -f http://localhost:8000/health || exit 1
        kill %1
