name: Dependency Audit
on:
  push:
    branches: [ clean-slate ]
  pull_request:
    branches: [ clean-slate ]

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          pip-audit -r requirements.txt -r requirements-dev.txt || true
