name: SBOM
on:
  workflow_dispatch:
  push:
    branches: [ clean-slate ]

jobs:
  cyclonedx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Generate SBOM
        run: |
          bash scripts/make_sbom.sh SBOM.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-json
          path: SBOM.json
