name: ZAP Baseline DAST
on:
  push:
    branches: [ clean-slate ]
  pull_request:
    branches: [ clean-slate ]

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install & start API
        run: |
          pip install -r requirements.txt
          uvicorn genomevault.api.app:app --port 8001 --host 0.0.0.0 &
          sleep 5
      - name: ZAP Baseline Scan
        if: ${{ false }}
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://127.0.0.1:8001'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_scan/*.*
